service: aws-chapgpt-linebot
provider:
  name: aws
  stage: dev
  region: us-east-1
  runtime: python3.9
  environment:
    Channel_access_token: jgopk6g6Go1l5q8EozTbI+zB9Itz/cbm7P2imEG+L/gkZa1nU3He1AywEKsfItw4eR4LgcuRLmeHduhypPwelTXvuUOWGKHwZC82utANrLoqqMNGWbiKwTu43mKIpi4vxLDrp6PvK0DO/CzbRlHaBgdB04t89/1O/w1cDnyilFU= 
    Channel_secret: 2276916d6dd75896b1df07da6b44c36e 
    openAI_API_token: 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 
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource:
            - "arn:aws:dynamodb:${aws:region}:*:table/chat-conversation-table"

functions:
  line_bot:
    handler: handler.webhook
    events:
      - http:
          path: /webhook
          method: POST

plugins:
  - serverless-python-requirements

resources:
  Resources:
    ConversationTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: chat-conversation-table
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
